name: expnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - cudatoolkit=11.1.1=hb139c0e_12
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - libnsl=2.0.0=hd590300_1
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.0.9=he6b73bb_1
  - libuv=1.46.0=hd590300_0
  - libzlib=1.2.13=hd590300_5
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.4=hcb278e6_0
  - nettle=3.6=he412f7d_0
  - ninja=1.11.1=h924138e_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=3.1.3=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=4_cp37m
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.43.0=h2c6b66d_0
  - tk=8.6.13=h2797004_0
  - torchaudio=0.9.0=py37
  - torchvision=0.10.0=py37_cu111
  - typing_extensions=4.7.1=pyha770c72_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - beautifulsoup4==4.12.2
      - cachetools==5.3.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - cycler==0.11.0
      - filelock==3.12.2
      - fonttools==4.38.0
      - fvcore==0.1.5.post20221221
      - gdown==4.7.1
      - h5py==3.8.0
      - idna==3.4
      - iopath==0.1.10
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-ml-py==12.535.133
      - nvitop==1.3.1
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==1.3.5
      - pillow==9.5.0
      - portalocker==2.7.0
      - psutil==5.9.6
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - soupsieve==2.4.1
      - tabulate==0.9.0
      - tensorrt==8.5.3.1
      - termcolor==2.3.0
      - thop==0.1.1-2209072238
      - torch==1.13.1
      - torch-tensorrt==1.3.0
      - tqdm==4.66.1
      - urllib3==2.0.6
      - yacs==0.1.8
prefix: /home/arpitsah/anaconda3/envs/expnet
